# Generated by Django 4.2.16 on 2025-02-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=199)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=90)),
                ("education", models.TextField()),
                ("skills", models.TextField()),
                ("experience", models.TextField()),
            ],
        ),
    ]
